module.exports = [
    './gulp/tasks/clean',
    './gulp/tasks/copyFonts',
    './gulp/tasks/copyImg',
    './gulp/tasks/copyJs',
    './gulp/tasks/copyLibs',
    './gulp/tasks/importJsBlocks',
    './gulp/tasks/importLibs',
    './gulp/tasks/js',
    './gulp/tasks/pug',
    './gulp/tasks/scssCompile',
    './gulp/tasks/scssConcat',
    './gulp/tasks/scss',
    './gulp/tasks/buildVue',
    './gulp/tasks/watchers',
    './gulp/tasks/serve',
    './gulp/tasks/server',
];